name: publish_docker_image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: container/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: container/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: container/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: container/build-push-action@v2
        with:
          push: true
          tags: tuteco/python-container-devtools:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}